name: qr_scanner_pro
description: QR Scanner Pro
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.7
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  google_mlkit_barcode_scanning: ^0.10.0
  ambient_light: ^0.1.0
  permission_handler: ^11.3.0

  # 🔥 NEW: Sharing feature
  share_plus: ^7.2.1

  # 🔥 OPTIONAL (for future: save/share QR as image)
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons.png